services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_docker_container
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
